#########################################################
# This file has been automatically generated by gem2tgz #
#########################################################
# -*- encoding: utf-8 -*-
# stub: pdfbeads 1.1.1 ruby lib

Gem::Specification.new do |s|
  s.name = "pdfbeads".freeze
  s.version = "1.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Alexey Kryukov".freeze]
  s.date = "2014-01-30"
  s.description = "    PDFBeads is a small utility written in Ruby which takes scanned\n    page images and converts them into a single PDF file. Unlike other\n    PDF creation tools, PDFBeads attempts to implement the approach\n    typically used for DjVu books. Its key feature is separating scanned\n    text (typically black, but indexed images with a small number of\n    colors are also accepted) from halftone pictures. Each type of\n    graphical data is encoded into its own layer with a specific\n    compression method and resolution.\n".freeze
  s.email = "amkryukov@gmail.com".freeze
  s.executables = ["pdfbeads".freeze]
  s.extra_rdoc_files = ["COPYING".freeze, "ChangeLog".freeze, "README".freeze]
  s.files = ["COPYING".freeze, "ChangeLog".freeze, "README".freeze, "bin/pdfbeads".freeze, "doc/pdfbeads.en.html".freeze, "doc/pdfbeads.ru.html".freeze, "lib/imageinspector.rb".freeze, "lib/pdfbeads.rb".freeze, "lib/pdfbeads/pdfbuilder.rb".freeze, "lib/pdfbeads/pdfdoc.rb".freeze, "lib/pdfbeads/pdffont.rb".freeze, "lib/pdfbeads/pdflabels.rb".freeze, "lib/pdfbeads/pdfpage.rb".freeze, "lib/pdfbeads/pdftoc.rb".freeze]
  s.homepage = "http://pdfbeads.rubyforge.org".freeze
  s.licenses = ["GPL".freeze]
  s.requirements = ["RMagick, v2.13.0 or greater".freeze, "nokogiri, v1.5.10 or greater".freeze, "PDF::Reader, v1.0.0 or greater".freeze]
  s.rubygems_version = "3.1.2".freeze
  s.summary = "PDFBeads -- convert scanned images to a single PDF file.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<nokogiri>.freeze, [">= 1.5.10"])
    s.add_runtime_dependency(%q<pdf-reader>.freeze, [">= 1.0.0"])
    s.add_runtime_dependency(%q<rmagick>.freeze, [">= 2.13.0"])
  else
    s.add_dependency(%q<nokogiri>.freeze, [">= 1.5.10"])
    s.add_dependency(%q<pdf-reader>.freeze, [">= 1.0.0"])
    s.add_dependency(%q<rmagick>.freeze, [">= 2.13.0"])
  end
end
